"""Initial migration

Revision ID: 913091d7d09f
Revises: 
Create Date: 2024-11-28 22:40:22.328550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913091d7d09f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
